package ExceptionHandling;

import java.util.Scanner;

public class TryCatch {
	public static void main(String args[]) {
	Scanner sc=new Scanner(System.in);
	System.out.println("enter no1");
	int a=sc.nextInt();
	System.out.println("enter no 2");
	int b=sc.nextInt();
	try {
		int c=a/b;
		System.out.println("division"+c );
	}
	catch(ArithmeticException e) {
		System.out.println(e);
	}
	System.out.println("run cpde....");
	
	
	}
	

}
